package empresafp;

import java.awt.Desktop;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.*;
import javax.swing.JOptionPane;

public class JFramePrincipal extends javax.swing.JFrame {

    static List<Empresa> empresas = new ArrayList<>();

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        this.setTitle("EmpresaFP v0.1");
        empresas.add(new Empresa("Softdil", "https://softdil.com/", "Pontevedra"));
        empresas.add(new Empresa("Balidea", "https://www.balidea.com/", "Vigo"));
        empresas.add(new Empresa("Degaltec", "https://degaltec.com/", "Vilagarcía de Arousa"));
        empresas.add(new Empresa("ASM", "https://asm.es/", "Vigo"));
        empresas.add(new Empresa("Landin", "https://www.landin.es", "Poio"));
        empresas.add(new Empresa("Coremain", "https://www.coremain.com/", "Pontevedra"));

        mostrarEmpresas();

    }

    void mostrarEmpresas() {
        String[] contenido = new String[empresas.size()];

        for (int i = 0; i < empresas.size(); i++) {
            contenido[i] = empresas.get(i).toString();
        }

        lstEmpresas.setListData(contenido);
    }

    boolean stringToFile(String[] cads, String nomeFicheiro) {
        boolean result = true;
        try {
            FileWriter ficheiro = new FileWriter(nomeFicheiro);
            PrintWriter pw = new PrintWriter(ficheiro);

            for (int i = 0; i < cads.length; i++) {
                pw.println(cads[i]);
            }

            ficheiro.close();

        } catch (IOException ex) {
            result = false;
        }
        return result;
    }

    void AbrirURL(String url) {
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(url));
            } catch (URISyntaxException e) {
                System.err.println("Error: Sintaxis de URL incorrecta.\n" + e.getMessage());
            } catch (IOException e) {
                System.err.println("Error: No se pudo abrir el enlace.\n" + e.getMessage());
            }
        } else {
            System.err.println("Error: Error de compatibilidad en la plataforma actual. No se puede abrir enlaces web.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmpresas = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniNuevaEmpresa = new javax.swing.JMenuItem();
        mniExportarCsv = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniNombreAsc = new javax.swing.JMenuItem();
        mniNombreDesc = new javax.swing.JMenuItem();
        mniConcelloAsc = new javax.swing.JMenuItem();
        mniConcelloDesc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstEmpresas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstEmpresas);

        jMenu1.setText("Fichero");

        mniNuevaEmpresa.setText("Nueva Empresa");
        mniNuevaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNuevaEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(mniNuevaEmpresa);

        mniExportarCsv.setText("Exportar .csv ...");
        mniExportarCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExportarCsvActionPerformed(evt);
            }
        });
        jMenu1.add(mniExportarCsv);

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mniSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ordenar");

        mniNombreAsc.setText("Nombre Asc");
        mniNombreAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNombreAscActionPerformed(evt);
            }
        });
        jMenu2.add(mniNombreAsc);

        mniNombreDesc.setText("Nombre Desc");
        mniNombreDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNombreDescActionPerformed(evt);
            }
        });
        jMenu2.add(mniNombreDesc);

        mniConcelloAsc.setText("Concello Asc");
        mniConcelloAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConcelloAscActionPerformed(evt);
            }
        });
        jMenu2.add(mniConcelloAsc);

        mniConcelloDesc.setText("Concello Desc");
        mniConcelloDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConcelloDescActionPerformed(evt);
            }
        });
        jMenu2.add(mniConcelloDesc);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniNombreAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNombreAscActionPerformed
        empresas.sort(new Comparator<Empresa>() {
            @Override
            public int compare(Empresa o1, Empresa o2) {
                return o1.nombre.compareTo(o2.nombre);
            }
        });
        mostrarEmpresas();
    }//GEN-LAST:event_mniNombreAscActionPerformed

    private void mniNombreDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNombreDescActionPerformed
        empresas.sort(new Comparator<Empresa>() {
            @Override
            public int compare(Empresa o1, Empresa o2) {
                return o2.nombre.compareTo(o1.nombre);
            }
        });
        mostrarEmpresas();
    }//GEN-LAST:event_mniNombreDescActionPerformed

    private void mniConcelloAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConcelloAscActionPerformed
        empresas.sort(new Comparator<Empresa>() {
            @Override
            public int compare(Empresa o1, Empresa o2) {
                return o1.concello.compareTo(o2.concello);
            }
        });
        mostrarEmpresas();
    }//GEN-LAST:event_mniConcelloAscActionPerformed

    private void mniConcelloDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConcelloDescActionPerformed
        empresas.sort(new Comparator<Empresa>() {
            @Override
            public int compare(Empresa o1, Empresa o2) {
                return o2.concello.compareTo(o1.concello);
            }
        });
        mostrarEmpresas();
    }//GEN-LAST:event_mniConcelloDescActionPerformed

    private void mniExportarCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExportarCsvActionPerformed
        String nombreFichero = JOptionPane.showInputDialog(this, "Nombre del fichero .csv");

        String[] contenido = new String[empresas.size()];

        for (int i = 0; i < empresas.size(); i++) {
            Empresa e = empresas.get(i);
            contenido[i] = e.nombre + "," + e.web + "," + e.concello;
        }

        stringToFile(contenido, nombreFichero);

    }//GEN-LAST:event_mniExportarCsvActionPerformed

    private void mniNuevaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNuevaEmpresaActionPerformed
        new JDialogNuevaEmpresa(this, true).setVisible(true);
        mostrarEmpresas();
    }//GEN-LAST:event_mniNuevaEmpresaActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_mniSalirActionPerformed

    private void lstEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpresasMouseClicked
       
        int indice = this.lstEmpresas.getSelectedIndex();
        String url = empresas.get(indice).web;
        AbrirURL(url);
    }//GEN-LAST:event_lstEmpresasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstEmpresas;
    private javax.swing.JMenuItem mniConcelloAsc;
    private javax.swing.JMenuItem mniConcelloDesc;
    private javax.swing.JMenuItem mniExportarCsv;
    private javax.swing.JMenuItem mniNombreAsc;
    private javax.swing.JMenuItem mniNombreDesc;
    private javax.swing.JMenuItem mniNuevaEmpresa;
    private javax.swing.JMenuItem mniSalir;
    // End of variables declaration//GEN-END:variables
}
